### PR TITLE
update REQUIRE and tests to 0.5 style

### PR DESCRIPTION
**Pull request by Evizero**
Just some misc fixes and updates.

- Base.Test instead of FactCheck
- Reduce dependencies to minimum
- Cleanup REQUIRE files
- Update CI configs
- Remove trailing whitespaces

### CODE REVIEW

**Comment by Evizero** [comment]
This PR would break the current state of #5, because it changes the test logic and such

**Comment by Evizero** [comment]
Has anyone enables `AppVeyor` by the way? We should add the badge to the readme.

**Comment by mronian** [comment]
Thanks for doing this @Evizero 😄 ! AppVeyor is not enabled yet. Could you do it along with this?

**Comment by timholy** [comment]
I just turned it on for ImageDraw and ImageFeatures, though perhaps @Evizero did too (I see it's running now).

**Comment by Evizero** [comment]
> I just turned it on for ImageDraw and ImageFeatures, though perhaps Evizero did too

I did, yes. Maybe to hastily. I wonder what happens if two people activate it.

**Comment by Evizero** [comment]
It is probably better if it is on you accound @timholy . I'll delete it on mine. Could you post the badge link here so I can change it to the readme?

**Comment by mronian** [comment]
Shall I merge this?

**Comment by Evizero** [comment]
@timholy The main thing missing is the AppVeyor badge, that I am afraid only you can look up. (appveyor uses some unique hash in the badge image link)

Aside from that, I think it is merge ready. #5 would need updating though, since its tests are then outdated. I am also ok with waiting for #5 to be merged and fix its tests here.

**Comment by timholy** [comment]
I'll update the badge after this merges. @tejus-gupta, is your "git-fu" (your comfort level with using `git`) up to rebasing? If not, I'd recommend we merge #5 first; a tricky rebase is not exactly the kind of thing I'd wish on *anyone* until they've had a good long while to become comfortable with git. I suspect @Evizero could do it in his sleep, which is why I'm more comfortable abusing him :smile:.

**Comment by Evizero** [comment]
I am perfectly fine with merging #5 first

**Comment by Evizero** [comment]
I did a squash rebase on #5 here, so if the tests here succeed I'd say #5 is ready to merge.

- we can either merge the PR #5 and then do a quick rebase here on master, or
- we can merge this PR which now includes #5 as a single squashed commit.

**Comment by Evizero** [comment]
(we should maybe do something about that coveralls overkill)

**Comment by mronian** [comment]
Merged! Thanks @Evizero 😄

**Pull request merged**
