### PR TITLE
Fix CI testing

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by Evizero** [comment]
Is `Images` really needed? It looks more like a rouge `using` to me https://github.com/JuliaImages/ImageDraw.jl/blob/master/test/paths.jl#L1

**Comment by Evizero** [comment]
Just tested it locally. removing `Images` works

**Comment by Evizero** [comment]
Ah, you beat me to it :)

**Comment by timholy** [comment]
You're so right. I think it was being used to load `ColorTypes` and `FixedPointNumbers` if that file was run as a standalone.

**Pull request merged**
